language: node_js
node_js: 
  - "12"
script:
  - npm install
  - npm run build
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN